{{/*
Merge default values with provided values to allow "deep merging"
Otherwise, sub-values will get undefined if parent object is overwritten
*/}}
{{- define "common.withMergedValues" -}}
{{- $templateName := .templateName -}}
{{- $context := .context -}}
{{- if hasKey $context "Subcharts" -}}
{{- $merged := merge $context.Values $context.Subcharts.common.Values -}}
{{- $ctx := dict "Values" $merged "Chart" $context.Subcharts.common.Chart "Release" $context.Release "Capabilities" $context.Capabilities "Files" $context.Subcharts.common.Files -}}
{{- include $templateName $ctx -}}
{{- else -}}
{{- include $templateName $context -}}
{{- end -}}
{{- end -}}
