name: Production Release

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write

jobs:
  release-production:
    name: Build and Release Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: version
        uses: starburst997/auto-version@v1

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Package and Push Charts
        run: |
          for chart_dir in charts/*/; do
            chart_name=$(basename $chart_dir)
            helm package "$chart_dir" \
              --version=${{ steps.version.outputs.version }}
            helm push ${chart_name}-${{ steps.version.outputs.version }}.tgz \
              oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
          done

          # Make the chart package public
          for chart_dir in charts/*/; do
            chart_name=$(basename $chart_dir)
            curl -X PATCH \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/user/packages/container/${{ github.repository_owner }}%2Fcharts%2F${chart_name}/versions \
              -d '{"visibility":"public"}' || true
          done

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
